### ISSUE TITLE
Macro Rendering Error causing some pages to be broken

### ISSUE THREAD

**Issue by z-proy** [knative/docs#4842]
## Expected Behavior
This webpage load correctly and display expected instructions: https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/

## Actual Behavior
Whatever framework you're using prints out the following error:

Macro Rendering Error[¶](https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/#macro-rendering-error)

AttributeError: 'str' object has no attribute 'removeprefix'

Traceback (most recent call last):
  File "/opt/buildhome/python3.8/lib/python3.8/site-packages/mkdocs_macros/plugin.py", line 473, in render
    return md_template.render(**page_variables)
  File "/opt/buildhome/python3.8/lib/python3.8/site-packages/jinja2/environment.py", line 1291, in render
    self.environment.handle_exception()
  File "/opt/buildhome/python3.8/lib/python3.8/site-packages/jinja2/environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "<template>", line 14, in top-level template code
  File "/tmp/tmp.AxXj2mTWoX/docs-1.3/hack/macros.py", line 97, in artifact
    version = drop_prefix(version)
  File "/tmp/tmp.AxXj2mTWoX/docs-1.3/hack/macros.py", line 13, in drop_prefix
    tag = tag.removeprefix("knative-")
AttributeError: 'str' object has no attribute 'removeprefix'
## Steps to Reproduce the Problem

1. Navigate to https://knative.dev/docs/install/yaml-install/serving/install-serving-with-yaml/ in any web browser

**Comment by carlisia** [comment]
This page also presents this error: https://knative.dev/docs/serving/using-auto-tls/

I'm going to change the title of this issue to reflect this more general issue.

**Comment by dprotaso** [comment]
Fix is incoming: https://github.com/knative/docs/pull/4843

**Comment by dprotaso** [comment]
Ok the website was pushed and it should be working as expected
