### ISSUE TITLE
Install knative failed by operator

### ISSUE THREAD

**Issue by life-learner1** [knative/docs#5245]
## Expected Behavior
install successfully
## Actual Behavior
knative-operator pod is restarted over and over again,  below is the error log
```text
I0926 02:28:41.712058       1 leaderelection.go:258] successfully acquired lease default/knative-operator.knative.dev.operator.pkg.reconciler.knativeserving.reconciler.00-of-01
{"severity":"INFO","timestamp":"2022-09-26T02:28:41.71231348Z","logger":"knative-operator","caller":"leaderelection/context.go:158","message":"\"knative-operator-6574f86bbc-rrftr_0b8911e5-6beb-4626-844b-6e6261fff35c\" has started leading \"knative-operator.knative.dev.operator.pkg.reconciler.knativeserving.reconciler.00-of-01\"","knative.dev/pod":"knative-operator-6574f86bbc-rrftr"}
{"severity":"INFO","timestamp":"2022-09-26T02:28:41.718587488Z","logger":"knative-operator","caller":"knativeserving/knativeserving.go:81","message":"Deleting cluster-scoped resources","knative.dev/pod":"knative-operator-6574f86bbc-rrftr","knative.dev/controller":"knative.dev.operator.pkg.reconciler.knativeserving.Reconciler","knative.dev/kind":"operator.knative.dev.KnativeServing","knative.dev/traceid":"c79175b5-6dac-4bd4-b2b8-81c022743656","knative.dev/key":"knative-serving/knative-serving"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1188498]

goroutine 595 [running]:
k8s.io/apimachinery/pkg/apis/meta/v1/unstructured.(*Unstructured).GetKind(...)
	k8s.io/apimachinery@v0.23.8/pkg/apis/meta/v1/unstructured/unstructured.go:226
github.com/manifestival/manifestival.okToDelete(0x0)
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:234 +0x38
github.com/manifestival/manifestival.Manifest.delete({{0xc0000b8a00, 0x34, 0x40}, {0x1e49818, 0xc0008c68c0}, {{0x1e4b938, 0xc00073a660}, 0x0}}, 0x1e49818?, {0x0, ...})
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:179 +0xae
github.com/manifestival/manifestival.Manifest.Delete({{0xc0000b8a00, 0x34, 0x40}, {0x1e49818, 0xc0008c68c0}, {{0x1e4b938, 0xc00073a660}, 0x0}}, {0x0, 0x0, ...})
	github.com/manifestival/manifestival@v0.7.1/manifestival.go:116 +0x1e5
knative.dev/operator/pkg/reconciler/common.Uninstall(0xc000d7fbc0)
	knative.dev/operator/pkg/reconciler/common/install.go:77 +0x278
knative.dev/operator/pkg/reconciler/knativeserving.(*Reconciler).FinalizeKind(0xc00054ec40, {0x1e49700, 0xc000d96660}, 0xc0003a87e0?)
	knative.dev/operator/pkg/reconciler/knativeserving/knativeserving.go:87 +0x36f
knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving.(*reconcilerImpl).Reconcile(0xc000417400, {0x1e49700, 0xc000d96630}, {0xc00057d120, 0x1f})
	knative.dev/operator/pkg/client/injection/reconciler/operator/v1beta1/knativeserving/reconciler.go:240 +0x3fe
knative.dev/pkg/controller.(*Impl).processNextWorkItem(0xc0003bf8c0)
	knative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:542 +0x58d
knative.dev/pkg/controller.(*Impl).RunContext.func3()
	knative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:491 +0x68
created by knative.dev/pkg/controller.(*Impl).RunContext
	knative.dev/pkg@v0.0.0-20220705130606-e60d250dc637/controller/controller.go:489 +0x312
```
## Steps to Reproduce the Problem

1. AWS EKS in China
2. replace gcr.io with gcr.dockerproxy.com
3. kubectl apply -f https://github.com/knative/operator/releases/download/knative-v1.6.1/operator.yaml

**Comment by abrennan89** [comment]
Please open an issue in the [operator repo](https://github.com/knative/operator/issues) or ask for help in the Knative Slack instead, since docs cannot solve this issue without someone first figuring out the root cause.
